services:
    "discord-ntfy-relay":
        image: "discord-ntfy-relay"
        build: .
        environment:
         - DISCORD_USERNAME=YOURUSER
         - DISCORD_TOKEN=TOKEN
         - NTFY_USERNAME=YOURUSER
         - NTFY_PASSWORD=YOURPASS
         - NTFY_URL=YOURNTFYSUBSCRIPTIONURL
        restart: always
        deploy:
          resources:
           limits:
            memory: 512M
